# Generated by Django 4.1.7 on 2023-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Developer', 'Developer'), ('Employee', 'Employee')], default=4, null=True),
        ),
    ]
