# Generated by Django 4.1.7 on 2023-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Seller'), (3, 'Developer'), (4, 'Employee')], default=4, null=True),
        ),
    ]
