# Generated by Django 4.1.7 on 2023-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TEXT'), (2, 'FILE')], default=1, null=True)),
                ('text', models.TextField(max_length=255)),
                ('send_time', models.DateTimeField()),
            ],
        ),
    ]
