# Generated by Django 4.1.7 on 2023-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='send_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TEXT'), (2, 'FILE')], default=1, null=True),
        ),
    ]
