# Generated by Django 4.1.7 on 2023-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_avatar',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
