# Generated by Django 4.1.7 on 2023-05-20 15:43

import base.services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_topic', models.CharField(max_length=50)),
                ('task_number_of_performing', models.IntegerField()),
                ('task_count_of_performing', models.IntegerField(default=0)),
                ('task_description', models.CharField(max_length=255)),
                ('task_deadline', models.DateField()),
                ('task_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ожидает исполнителя'), (2, 'В работе'), (3, 'На проверке'), (4, 'Принят')], default=1, null=True)),
                ('task_flag', models.CharField(max_length=50)),
                ('task_file', models.FileField(blank=True, null=True, upload_to=base.services.get_path_file)),
                ('task_executors', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
