# Generated by Django 4.1.7 on 2023-05-26 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_task_executors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_executors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
